# Generated by Django 4.0.3 on 2022-06-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
